<?php

$lang['useful_site_links_text_1'] = "1. <a href='http://www.autismspeaks.org' target='_blank'>www.autismspeaks.org</a> - One of the leading autism science and advocacy organizations. Autism Speaks provides a comprehensive resource guide for all states. The site also boasts an impressive list of apps that parents may find useful, including games that focus on communication and social skills.";
$lang['useful_site_links_text_2'] = "2. <a href='http://www.autism-society.org' target='_blank'>www.autism-society.org</a> - Another great site that includes helpful resources for those with autism,  family members, as well as professionals. Autism Society also gives updates on the latest autism news and press releases.";
$lang['useful_site_links_text_3'] = "3. <a href='http://www.disabilityscoop.com' target='_blank'>www.disabilityscoop.com</a> – Sign up for Disability Scoop’s e-mail news to receive the most current updates on developmental disabilities. Disability Scoop’s experts have been cited by multiple online news sites, including USA Today and People.com.";
$lang['useful_site_links_text_4'] = "4. <a href='http://www.autismnj.org' target='_blank'>www.autismnj.org</a> - Run by a network of professionals and parents, Autism New Jersey strives to provide New Jersey residents affected by autism with the most up to date information, including info on Health Care and insurance mandates in New Jersey.";
$lang['useful_site_links_text_5'] = "5. <a href='http://www.autism.com' target='_blank'>www.autism.com</a> - The Autism Research Institute focuses on researching the causes of autism, as well as developing safe and effective treatments for those currently affected by the disorder.";
$lang['useful_site_links_text_6'] = "6. <a href='http://www.autismweb.com' target='_blank'>www.autismweb.com</a> – Managed by parents, AutismWeb includes great insights on different autism teaching methods. The site also  provides a forum where parents can go to share their stories, give updates on their children’s progress, and share recipes that may be useful for picky eaters.";
$lang['useful_site_links_text_7'] = "7. <a href='http://www.ahany.org' target='_blank'>www.ahany.org</a> – The Asperger Syndrome and High Functioning Autism Association website offers some great resources for those with higher functioning autism. Ahany also provides a great list  of summer programs and day camps in New York, as well as useful questions to ask when choosing a camp or summer program for your special needs child.";
$lang['useful_site_links_text_8'] = "8. <a href='http://www.autismhwy.com' target='_blank'>www.autismhwy.com</a> - Started by a woman whose son was diagnosed with autism, Autism Highway is both informative and fun. Easy to navigate, Autism Highway provides an extensive list of Autism related events and specialists. In addition, Autism Highway includes many fun games that children are sure to enjoy!";
$lang['useful_site_links_text_9'] = "9. <a href='http://www.autismbeacon.com' target='_blank'>www.autismbeacon.com</a> – Also started by the parent of a child with autism, Autism Beacon strives to supply the best resources for autism treatments. Autism Beacon presents a lengthy range of articles on autism, including sensitive topics such as bullying and sexuality.";
$lang['useful_site_links_text_10'] = "10. <a href='http://www.autischoolsrilanka.com' target='_blank'>www.autischoolsrilanka.com</a> - When my son Timothy was almost 4 years old, we realized that his behavior had changed. From 2 years old his speech did not improve as well. As he was taught in 2 languages (Dutch and English) we however did not worry about that too much. After going to a normal pre-school, it appeared that Timothy had a problem and we did several tests and assessments with him, resulting in the diagnoses of autism and mental retardation.";
$lang['useful_site_links_text_11'] = "11. <a href='http://www.saaac.org' target='_blank'>www.saaac.org</a> - SAAAC is a non profit community organization established in 2008. We are composed of a multi-disciplinary team including physicians, behavioural therapists, speech therapists, occupational therapists, dance/music therapists, and social workers. Our coordinated team aims to provide easily accessible and discipline-rich management for Autism Spectrum Disorder (ASD). Our organization looks to target South Asian families who often do not benefit from resource awareness or engagement, which are crucial and timely to the successful development of their children.";
